### ISSUE TITLE
Not possible to bootstrap Spot Instance from userdata

### ISSUE THREAD

**Issue by andreivmaksimov** [awslabs/ec2-spot-labs#9]
Hi,

I'm trying to spin up ec2 spot instances and attach them to my EKS cluster, but your user-data instructions specified in [https://github.com/awslabs/ec2-spot-labs/blob/master/ec2-spot-eks-solution/provision-worker-nodes/amazon-eks-nodegroup-with-spot.yaml](https://github.com/awslabs/ec2-spot-labs/blob/master/ec2-spot-eks-solution/provision-worker-nodes/amazon-eks-nodegroup-with-spot.yaml) are not working:

```
aws eks describe-cluster --region=us-east-1 --service-name=aws-eks-spot-serverless-demo-dev --query 'cluster.{certificateAuthorityData: certificateAuthority.data, endpoint: endpoint}' --debug
2018-09-23 17:40:03,396 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.13 Python/2.7.14 Linux/4.14.62-70.117.amzn2.x86_64 botocore/1.12.3
2018-09-23 17:40:03,397 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['eks', 'describe-cluster', '--region=us-east-1', '--service-name=aws-eks-spot-serverless-demo-dev', '--query', 'cluster.{certificateAuthorityData: certificateAuthority.data, endpoint: endpoint}', '--debug']
2018-09-23 17:40:03,397 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f9b98c43758>
2018-09-23 17:40:03,397 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-23 17:40:03,398 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f9b92696ed8>
2018-09-23 17:40:03,398 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-23 17:40:03,398 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f9b92663230>
2018-09-23 17:40:03,398 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-23 17:40:03,398 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2018-09-23 17:40:03,399 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2018-09-23 17:40:03,399 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-23 17:40:03,399 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2018-09-23 17:40:03,399 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-23 17:40:03,399 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2018-09-23 17:40:03,400 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-23 17:40:03,401 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f9b91e501b8>
2018-09-23 17:40:03,401 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-23 17:40:03,401 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-23 17:40:03,401 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-09-23 17:40:03,402 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /root/.aws/models/eks/2017-11-01/service-2.json
2018-09-23 17:40:03,418 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.eks: calling handler <function register_retries_for_service at 0x7f9b9383c7d0>
2018-09-23 17:40:03,418 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 207, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 341, in __call__
    service_parser = self._create_parser()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 381, in _create_parser
    command_table = self._get_command_table()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 326, in _get_command_table
    self._command_table = self._create_command_table()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 348, in _create_command_table
    service_model = self._get_service_model()
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line 334, in _get_service_model
    self._service_name, api_version=api_version)
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 540, in get_service_model
    service_description = self.get_service_data(service_name, api_version)
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 568, in get_service_data
    service_name=service_name, session=self)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/handlers.py", line 278, in register_retries_for_service
    service_event_name = hyphenize_service_id(service_id)
  File "/usr/lib/python2.7/site-packages/botocore/utils.py", line 981, in hyphenize_service_id
    return service_id.replace(' ', '-').lower()
AttributeError: 'NoneType' object has no attribute 'replace'
2018-09-23 17:40:03,419 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'NoneType' object has no attribute 'replace'
``` 

I guess something wrong with model.

**AMI** (official from AWS documentation): ami-0440e4f6b9713faf6
```
aws --version
aws-cli/1.16.13 Python/2.7.14 Linux/4.14.62-70.117.amzn2.x86_64 botocore/1.12.3
```

**Comment by andreivmaksimov** [comment]
Seems to be the same issue: [https://github.com/aws/aws-cli/issues/3602](https://github.com/aws/aws-cli/issues/3602)

**Comment by andreivmaksimov** [comment]
We may close the issue. It is privileges problem. All I can add here, is that it is possible to use latest version of awscli and not load the json model. More over, in that case you may use official AMIs from the [EKS UserGuide](https://docs.aws.amazon.com/eks/latest/userguide/what-is-eks.html)
